remote-services:
  serviceConfigs:
    - url: https://api.openai.com
      name: OpenAI
      api-key: sk-Nguzl57Q54aBhqV8xvTYhbQsBSOQb2Zx2umHeHOGsVT3BlbkFJEk-noLr87JWlmJ9gg1fSoYMS-F2NaCBZtzxFWdcPEA
      allowed-models:
        - gpt-3.5-turbo
        - gpt-3.5-turbo-0125
