name: CI - npm start check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  npm-start-check:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust based on the version your project uses

    # Install npm dependencies from the gpt-clone folder
    - name: Install dependencies
      working-directory: gpt-clone
      run: npm install

    # Test if npm start works from the gpt-clone folder
    - name: Run npm start
      working-directory: gpt-clone
      run: npm start
