name: CI - npm build and serve check

on:
  push:
    branches:
      - main
      - cicdTest
  pull_request:
    branches:
      - main

jobs:
  npm-build-check:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on the version your project uses

      # Install npm dependencies from the gpt-clone folder
      - name: Install dependencies
        working-directory: gpt-clone
        run: npm install

      # Build the project instead of starting dev server
      - name: Build production version
        working-directory: gpt-clone
        run: npm run build

      # Install 'serve' to run the production build
      - name: Install serve
        run: npm install -g serve

      # Serve the production build
      - name: Start production server
        working-directory: gpt-clone/build
        run: serve -s .
